### ISSUE TITLE
Problem uploading sketch.

### ISSUE THREAD

**Issue by DP777** [tbattz/DIYLoadCellSimRacingPedals#1]
First of all, THANK YOU for providing this file.
Here's the problem:
After I include the HX711 and Joystick libraries, when I click "Verify" or "Upload", an error message pops up: 

C:\Users\DP\Documents\Arduino\libraries\HX711-master\src/HX711.h:19:7: note:   candidate expects 1 argument, 2 provided
exit status 1
no matching function for call to 'HX711::HX711(int, int)'

Hope you can help me with this issue (I'm new to arduino).

*If I remove (0, 1)    it seems to upload just fine.

**Comment by tbattz** [comment]
Are you using verify on the script as is here, or have you made a couple of changes to it?

I can get the same error if I change line 14 to HX711 throttleScale(0,1), but it should just be HX711 throttleScale as in the original, as for the HX711 class we don't set the pins on initialisation.

Under // Setup HX711 boards, we're creating the class HX711.
``` cpp
// Setup HX711 boards
HX711 throttleScale;
HX711 brakeScale;
```
Then on line 66, we set the pins for the class instance.
``` cpp
// Setup first HX711
throttleScale.begin(DOUT, CLK);
throttleScale.set_scale();
throttleScale.tare(); // Set scale to 0
long zero_factor = throttleScale.read_average();
  
// Setup second HX711
brakeScale.begin(DOUT2, CLK2);
brakeScale.set_scale();
brakeScale.tare(); // Set scale to 0
long zero_factor2 = brakeScale.read_average();
```
